#! /bin/bash
# Use rsync to back up the /home folder to the Linux partition on the 500 GB Toshiba USB drive
# --delete allows for deletion of files on the backup that have been previously deleted on the source drive
# setting up an exclude file to back up some directories and not others.
rsync -av --delete --exclude-from '/home/steven/Documents/shell_scripts/debian-squeeze/exclude' /home /media/Linux/debian
exit 0
